export const NEW_NOTE_REQUEST = 'NEW_NOTE_REQUEST'
export const NEW_NOTE_FAIL = 'NEW_NOTE_FAIL'
export const NEW_NOTE_SUCCESS = 'NEW_NOTE_SUCCESS'

export const DELETE_NOTE_REQUEST = "DELETE_NOTE_REQUEST"
export const DELETE_NOTE_FAIL = "DELETE_NOTE_FAIL"
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS"


export const UPDATE_NOTE_REQUEST = "UPDATE_NOTE_REQUEST"
export const UPDATE_NOTE_FAIL = "UPDATE_NOTE_FAIL"
export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS"

